### ISSUE TITLE
Network Interface ID Removal   

### ISSUE THREAD

**Issue by pnduati** [terraform-aws-modules/terraform-aws-ec2-instance#75] opened 2019-02-28 03:05 UTC
local.this_network_interface_id: Resource 'aws_instance.this_t2' does not have attribute 'network_interface_id' for variable 'aws_instance.this_t2.*.network_interface_id'
@antonbabenko @den-is

**Comment by danielwrayois** [comment] 2019-02-28 11:40
Hi,

This is likely to be related to the AWS 2.0 provider released yesterday by Hashicorp. If you aren't pinning your version to the AWS 1.60 provider you should do this until the issue is resolved in this module.

**Comment by antonbabenko** [comment] 2019-02-28 15:08
@pnduati Could you switch to `primary_network_interface_id` in #76 and I will merge that PR. This change will make this module 2.0.0-ready.

**Comment by pnduati** [comment] 2019-02-28 23:28
@antonbabenko @danielwrayois  We already have  primary_network_interface_id parameter in the outputs definition.  The PR removes the  network_interface_id, cause this is deprecated.

**Comment by antonbabenko** [comment] 2019-03-01 08:43
You are right, thanks for this fix.

[v1.19.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.19.0) has been released.

**Closed by antonbabenko** 2019-03-01 08:43 UTC
