### ISSUE TITLE
Issue while updating existing infrastructure

### ISSUE THREAD

**Issue by ranvijayj** [terraform-aws-modules/terraform-aws-ec2-instance#13] opened 2018-01-17 14:29 UTC
Hi,

Some details regarding the issue: https://github.com/hashicorp/terraform/issues/17120

@antonbabenko 

Also, Even if I update just the instance count in one module , it touches the route table resource and destroys instances in the other module as well and then fails. 

Any idea?

**Comment by ranvijayj** [comment] 2018-01-17 14:53
So, I do a terraform plan and apply 
then without changing anything I do a terraform plan it still shows changes...

**Comment by ranvijayj** [comment] 2018-01-17 15:10
Sorry for another message here but I do terraform apply once resources get created. Then I again run ter plan changes show up

https://gist.github.com/ranvijayj/e6e8443c1f440d77990adf505114e195

I see ` root_block_device.0.delete_on_termination:         "false" => "true" (forces new resource)` Is changing even though I made no change...

**Comment by ranvijayj** [comment] 2018-01-17 16:38
ran the same thing but without using this module but a simple aws instance resource and did plan and apply mutiple times nothing showed changed...

https://gist.github.com/ranvijayj/d604c1475f4d8dcb4f0912f0898a710c

Why is it happening just with the module?

**Comment by ranvijayj** [comment] 2018-01-18 05:17
@antonbabenko Terraform guys just replied on https://github.com/hashicorp/terraform/issues/17120

If that helps.

**Comment by ranvijayj** [comment] 2018-01-18 08:13
Code: https://drive.google.com/open?id=1__aoVg0ksNDz1r7hSfAv2gizr-erWBTu

@antonbabenko @apparentlymart

**Comment by antonbabenko** [comment] 2018-01-18 08:31
@ranvijayj I won't be able to look into this issue before the weekend. I may have time, but can't promise. Business trip.

**Comment by antonbabenko** [comment] 2018-01-22 10:07
Sorry for the delay in my response. I have just read the whole discussion, and the problem is in the following:
1. https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/main.tf#L37-L42 - these lifecycle rules were added in [v1.1.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/tag/v1.1.0) as a fix to the same issue as you are experiencing (see #10).
1. The code you have referred in [this comment](https://github.com/hashicorp/terraform/issues/17120#issuecomment-358540273) does not have required `lifecycle`, so it is not working as expected.

Closing this issue.

**Closed by antonbabenko** 2018-01-22 10:07 UTC
